services:
  app:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/cmd/app/Dockerfile
    container_name: subscription-env-app
    env_file:
      - ${PROJECT_ROOT}/.env
    environment:
      - HTTP_ADDR=:5050
      - POSTGRES_HOST=subscription-postgres
      - LOGGER_FOLDER=/app/out/logs
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    ports:
      - "5050:5050"
    restart: always

  subscription-postgres:
    image: postgres:18.1-bookworm
    container_name: subscription-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  subscription-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: subscription-env-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:subscription-postgres:5432
    ports:
      - "127.0.0.1:5432:5432"

  swagger:
    build:
      context: ${PROJECT_ROOT}
      dockerfile_inline: |
        FROM golang:1.25.0
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - ${PROJECT_ROOT}:/code

