FROM golang:1.25 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /app/exe ./cmd/app

FROM alpine:3.23 AS runner
WORKDIR /app

COPY --from=builder /app/exe /app/exe

ENV PROJECT_ROOT=/app
CMD ["/app/exe"]